

services:

  # gateway:
  #   image: nginx:alpine
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./Config/nginx.conf:/etc/nginx/conf.d/default.conf
  #     - ./Frontend/project-2-frontend/dist:/usr/share/nginx/html
  #   depends_on:
  #     - api

  api:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: Project-2-api
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://0.0.0.0:8080
    # env_file:
    #   - ./Config/.env
    volumes:
      - ./Config/appsettings.Production.json:/myApp/appsettings.Production.json
      - ./Config/logs.txt:/myApp/Logs/log.txt
    networks:
      - project-2-network

  frontend:
    build:
      context: "./Frontend/project-2-frontend"
      dockerfile: dockerfile
    container_name: Project-2-frontend
    ports:
      - "4200:80"
    depends_on:
      - api
    volumes:
      - ./Config/config.json:/usr/share/nginx/html/assets/config.json

    networks:
      - project-2-network

networks:
  project-2-network:
    driver: bridge
